all:
  children:
    collibra_servers:
      hosts:
        node1.example.com:
          ansible_ssh_private_key_file: /root/.ssh/<name>.pem
          ansible_user: ec2-user
        node2.example.com:
        node3.example.com:
        node4.example.com:
    postgres_servers:
      hosts:
        node1.example.com:
          ansible_ssh_private_key_file: /root/.ssh/<name>.pem
          ansible_user: ec2-user
        node2.example.com:
        node3.example.com:

