---
- name: Install PostgreSQL
  hosts: postgres_servers
  become: yes
  tasks:

    # Ensure system packages are updated
    - name: Update all packages to the latest version
      dnf:
        name: '*'
        state: latest
      when: ansible_os_family == "RedHat"

    # Install required packages
    - name: Install required packages
      dnf:
        name:
         - wget
         - python3
        state: latest

    # Verify repository file exists
    - name: Verify PostgreSQL repository file
      stat:
        path: /etc/yum.repos.d/pgdg-redhat.repo
      register: repo_file

    # Manually create the PostgreSQL repo file if missing
    - name: Ensure PostgreSQL repo file exists
      copy:
        dest: /etc/yum.repos.d/pgdg-redhat.repo
        content: |
          [pgdg14]
          name=PostgreSQL 14 for RHEL $releasever - $basearch
          baseurl=https://download.postgresql.org/pub/repos/yum/14/redhat/rhel-$releasever-$basearch
          enabled=1
          gpgcheck=0
      when: repo_file.stat.exists == False

    # Disable built-in PostgreSQL module to avoid conflicts
    - name: Disable built-in PostgreSQL module
      command: dnf module disable postgresql -y
      when: ansible_os_family == "RedHat"

    # Install PostgreSQL 14
    - name: Install PostgreSQL server and client
      dnf:
        name:
          - postgresql14
          - postgresql14-server
          - postgresql14-contrib
          - postgresql14-libs
        state: present
        disable_gpg_check: true


    # Update the /usr/lib/tmpfiles.d/postgresql-14.conf file
    - name: Update PostgreSQL tmpfiles configuration
      lineinfile:
        path: /usr/lib/tmpfiles.d/postgresql-14.conf
        regexp: '^d /run/postgresql'
        line: 'd /run/postgresql 2777 postgres postgres - -'
        state: present

    # Reboot the node
    - name: Reboot the node
      reboot:
        reboot_timeout: 600  # Adjust as necessary
        test_command: whoami  # This will check if the node is back up