---
- name: Install PostgreSQL
  hosts: postgres_servers
  become: yes
  tasks:

    # Ensure system packages are updated
    - name: Update all packages to the latest version
      dnf:
        name: '*'
        state: latest
      when: ansible_os_family == "RedHat"

    # Install required packages
    - name: Install required packages
      dnf:
        name:
         - wget
         - python3
        state: latest

    # Construct the URL dynamically and download the repository RPM
    - name: Construct URL and download PostgreSQL repository RPM
      shell: |
        url="https://download.postgresql.org/pub/repos/yum/reporpms/EL-$(rpm -E %{rhel})-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
        wget -O /tmp/pgdg-redhat-repo-latest.noarch.rpm $url
      args:
       creates: /tmp/pgdg-redhat-repo-latest.noarch.rpm

   # Check if PostgreSQL RPM is installed
   - name: Check if PostgreSQL repository RPM is installed
     shell: rpm -q pgdg-redhat-repo
     register: rpm_check
     ignore_errors: true

   # Notify the user if the RPM is already installed
   - name: Notify if PostgreSQL repository RPM is already installed
     debug:
       msg: "PostgreSQL repository RPM is already installed."
     when: rpm_check.rc == 0

   # Install PostgreSQL repository RPM if not installed
   - name: Install PostgreSQL repository
     dnf:
       name: /tmp/pgdg-redhat-repo-latest.noarch.rpm
       state: present
       disable_gpg_check: true
     when: rpm_check.rc != 0

   # Retrieve the GPG key for PostgreSQL
   - name: Retrieve the GPG key for PostgreSQL
     shell: |
       rpm --import https://download.postgresql.org/pub/repos/yum/RPM-GPG-KEY-PGDG
     args:
       creates: /etc/pki/rpm-gpg/RPM-GPG-KEY-PGDG


    # Verify repository file exists
    - name: Verify PostgreSQL repository file
      stat:
        path: /etc/yum.repos.d/pgdg-redhat.repo
      register: repo_file
      
    # Disable built-in PostgreSQL module to avoid conflicts
    - name: Disable built-in PostgreSQL module
      dnf:
        name: postgresql
        state: disabled
        module: true
      when: ansible_os_family == "RedHat"


    # Install PostgreSQL 14
    - name: Install PostgreSQL server and client
      dnf:
        name:
          - postgresql14
          - postgresql14-server
          - postgresql14-contrib
          - postgresql14-libs
        state: present
        disable_gpg_check: true

    # Update the /usr/lib/tmpfiles.d/postgresql-14.conf file
    - name: Update PostgreSQL tmpfiles configuration
      lineinfile:
        path: /usr/lib/tmpfiles.d/postgresql-14.conf
        regexp: '^d /run/postgresql'
        line: 'd /run/postgresql 2777 postgres postgres - -'
        state: present

    # Reboot the node
    - name: Reboot the node
      reboot:
        reboot_timeout: 600  # Adjust as necessary
        test_command: whoami  # This will check if the node is back up